sudo: false
language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION scala-junit-mixin-plugin/scalastyle testSuite/scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION testSuite/test
  - sbt ++$TRAVIS_SCALA_VERSION scala-junit-mixin-plugin/publishLocal
scala:
  - 2.12.0-M5
jdk:
  - oraclejdk8
